### ISSUE TITLE
Python2 support on Homebrew

### ISSUE THREAD

**Issue by atsokol** [r-spatial/RQGIS#118]
Hi!

I have been trying to following your instructions for installing GRASS, SAGA and QGIS on MacOS using Homebrew. However, all of those installations do not work after python@2 was deleted from homebrew/core from 1st Jan 2020. I was trying to find alternative sources for installing python2 but it didn't work. Is there any simple fix for this? Thanks.

P.S. Sorry, I am not very experienced in programming, just trying to upgrade my spatial data analysis skills in R

**Comment by pat-s** [comment]
Please do not use this package anymore and have a look at [RQGIS3](https://github.com/r-spatial/RQGIS3) which uses python3.

@jannes-m Can we archive this package?

**Comment by jannes-m** [comment]
Sure, we can archive it!
